---
# ------------------------------------------------------------------------------
- name: check for docker
  command: which docker
  register: docker_command
  failed_when: docker_command.rc != 0
  changed_when: false

# ------------------------------------------------------------------------------
- name: check for binary
  stat:
    path: /usr/local/bin/scope
  register: scope_binary

# ------------------------------------------------------------------------------
- name: stop scope
  command: scope stop
  when: scope_binary.stat is defined

# ------------------------------------------------------------------------------
- name: delete binary
  file:
    path: /usr/local/bin/scope
    state: absent
  when: scope_binary.stat is defined
...
