---
flannel_interface: "{{ ansible_default_ipv4.interface }}"
flannel_host_ipv4_address: "{{ hostvars[inventory_hostname]['ansible_' + flannel_interface].ipv4.address }}"
flannel_master_ipv4_address: "{{ hostvars[groups['master'][0]]['ansible_' + flannel_interface].ipv4.address }}"

flannel_etcd_client_port: "2379"
flannel_etcd_url_scheme: "http"
flannel_etcd_url: "{{ flannel_etcd_url_scheme }}:\\/\\/{{ flannel_master_ipv4_address }}:{{ flannel_etcd_client_port }}"
