---
- include_tasks: network-policy.yml

- include_tasks: subscriber.yml
  vars:
    rti_perftest_id_subscriber: "{{ item }}"
  with_sequence: count={{ rti_perftest_sub_count }}

- include_tasks: publisher.yml
