---
- name: "install"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - keepalived
  when: "'master' in group_names"

- name: "configuration : service"
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  register: kubernetes_keepalived_configuration_service
  when: "'master' in group_names"

- name: "configuration : health check script"
  template:
    src: check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh
    owner: root
    group: root
    mode: 0755
  register: kubernetes_keepalived_configuration_health_check_script
  when: "'master' in group_names"

- name: "service : enable and start"
  service:
    name: "keepalived.service"
    state: started
    enabled: yes
  when: "'master' in group_names"

- name: "service : restart"
  service:
    name: "keepalived.service"
    state: restarted
  when: ("'master' in group_names")
        and ((kubernetes_keepalived_configuration_service.changed
             or kubernetes_keepalived_configuration_health_check_script.changed))
