---
- name: get current routes
  command: "ip route"
  changed_when: no
  register: kubernetes_current_routes

- name: "add route for {{ kubernetes_service_cidr }} : session"
  command: "ip route replace {{ kubernetes_service_cidr }} dev {{ kubernetes_interface }} src {{ kubernetes_host_ipv4_address }}"
  when: not(kubernetes_current_routes.stdout | regex_search(kubernetes_service_cidr))

- name: "add route for {{ kubernetes_service_cidr }} : permanent"
  lineinfile:
    path: "/etc/sysconfig/network-scripts/route-{{ kubernetes_interface }}"
    regexp: "^.*{{ kubernetes_service_cidr }}.*$"
    line: "{{ kubernetes_service_cidr }} dev {{ kubernetes_interface }} src {{ kubernetes_host_ipv4_address }}"
    create: yes
#  when: not(kubernetes_current_routes.stdout | regex_search(kubernetes_service_cidr))
