---
# ------------------------------------------------------------------------------
- name: check for binary
  stat:
    path: /usr/local/bin/weave
  register: weave_binary

# ------------------------------------------------------------------------------
- name: check for docker
  command: which docker
  register: docker_command
  failed_when: docker_command.rc != 0
  changed_when: false
  when: weave_binary.stat.exists == true

# ------------------------------------------------------------------------------
- name: reset
  command: weave reset --force
  when: weave_binary.stat.exists == true

# ------------------------------------------------------------------------------
- name: delete binary
  file:
    path: /usr/local/bin/weave
    state: absent
  when: weave_binary.stat.exists == true
...
