---
# ------------------------------------------------------------------------------
- name: check for docker
  command: which docker
  register: docker_command
  failed_when: docker_command.rc != 0
  changed_when: false

# ------------------------------------------------------------------------------
- name: check for binary
  stat:
    path: /usr/local/bin/weave
  register: weave_binary

- name: download binary
  command: curl -L git.io/weave -o /usr/local/bin/weave creates=/usr/local/bin/weave
  when: weave_binary.stat.exists == false

- name: allow execution of binary
  file:
    path: /usr/local/bin/weave
    mode: "a+x"
  when: weave_binary.stat.exists == false

# ------------------------------------------------------------------------------
- name: status
  command: "/usr/local/bin/weave status"
  register: weave_status
  failed_when: false
  changed_when: false

# ------------------------------------------------------------------------------
- name: create directories for CNI plugin
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  when: weave_status.rc != 0
  with_items:
    - /opt/cni/bin
    - /etc/cni/net.d

- name: setup
  command: "/usr/local/bin/weave setup"
  when: weave_status.rc != 0

# ------------------------------------------------------------------------------
- name: launch
  command: "/usr/local/bin/weave launch {% for host in groups['centos'] if host != ansible_host %} {{ host }} {% endfor %}"
  when: weave_status.rc != 0
...
