---
- include: copy-certs.yml
  when:
    docker_private_repo_local_cert_path is defined
  
- include_role:
    name: docker/registry/kubernetes/create-secret
  vars:
    docker_registry_url: "{{ docker_private_registry_url }}"
    docker_registry_port: "{{ docker_private_registry_port }}"
    docker_registry_auth_user: "{{ docker_private_registry_auth_user }}"
    docker_registry_auth_password: "{{ docker_private_registry_auth_password }}"
    