---
# kubernetes_load_balancer_ip: 
kubernetes_keepalived_virtual_router_id: 1
kubernetes_keepalived_priority_master: 101
kubernetes_keepalived_priority_backup: 100
kubernetes_keepalived_auth_pass: super_secret_password
